theme: jekyll-theme-slate
title: Zhi Xu
# description: Undergraduate at SUSTech, China
# logo: /Pictures/Capsule.png
# url_cv: /docs/CV_Yulun_Zhuang.pdf
url_github: https://github.com/silvery107
url_email: z1079931505@gmail.com
icon: /Pictures/Capsule.png
